name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Run on all OSes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff black

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest

  build-release:
    if: startsWith(github.ref, 'refs/tags/')  # Only on tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build project
        run: |
          python setup.py sdist bdist_wheel

      - name: Create a release
        uses: gh-action-release/release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-artifact@v2
        with:
          name: pymuse-release
          path: bin/*